CREATE OR REPLACE VIEW VW_ANIMAIS_DISP_ADOCAO AS 

SELECT
	ID_ANIMAL,
    ESPECIE,
    NOME_RACA,
    NOME,
    GENERO,
    ESTADO,
    ADOTADO
FROM
    DB_ESPERANCA_VIVA.ANIMAIS AS A
    CROSS JOIN DB_ESPERANCA_VIVA.ESPECIES AS E 
    CROSS JOIN DB_ESPERANCA_VIVA.RACAS AS R
    CROSS JOIN DB_ESPERANCA_VIVA.SITUACOES AS S
WHERE A.ID_ESPECIE = E.ID_ESPECIE AND A.ID_RACA = R.ID_RACA AND A.ID_SITUACAO = S.ID_SITUACAO AND ADOTADO = 0;
