CREATE
OR REPLACE VIEW VW_DESPESAS_MENSAIS AS
SELECT
    REPLACE (
        CAST(FORMAT (SUM(VALOR_DESPESA), 2) AS CHAR),
        ',',
        '.'
    ) AS DESPESAS
FROM
    DB_ESPERANCA_VIVA.DESPESAS_MEDICAS
WHERE
    DATA_DESPESA BETWEEN '2024-10-01' AND '2024-10-30';