

CREATE TABLE DB_ESPERANCA_VIVA.ESPECIES(

    ID_ESPECIE SMALLINT AUTO_INCREMENT,
    ESPECIE  VARCHAR(30),
    PRIMARY KEY (ID_ESPECIE)
);

CREATE TABLE DB_ESPERANCA_VIVA.RACAS(

    ID_RACA SMALLINT  AUTO_INCREMENT,
    ID_ESPECIE SMALLINT NOT NULL,
    NOME_RACA VARCHAR(55),
    PRIMARY KEY (ID_RACA)

);

ALTER TABLE DB_ESPERANCA_VIVA.RACAS ADD CONSTRAINT FK_ESPECIE_1 FOREIGN KEY(ID_ESPECIE) REFERENCES DB_ESPERANCA_VIVA.ESPECIES (ID_ESPECIE);


CREATE TABLE DB_ESPERANCA_VIVA.SITUACOES(

    ID_SITUACAO SMALLINT AUTO_INCREMENT,
    ESTADO VARCHAR(40),
    PRIMARY KEY (ID_SITUACAO)

);

CREATE TABLE DB_ESPERANCA_VIVA.ANIMAIS(

    ID_ANIMAL INT AUTO_INCREMENT,
    ID_ESPECIE  SMALLINT NOT NULL,
    ID_RACA  SMALLINT NOT NULL,
    ID_SITUACAO  SMALLINT NOT NULL,
    NOME VARCHAR(50),
    GENERO CHAR (1),
    DATA_ADOCAO DATE,
    ID_CLIENTE INT,
    ADOTADO BIT,
    PRIMARY KEY (ID_ANIMAL)

);

ALTER TABLE DB_ESPERANCA_VIVA.ANIMAIS ADD CONSTRAINT FK_ESPECIE_2 FOREIGN KEY(ID_ESPECIE) REFERENCES DB_ESPERANCA_VIVA.ESPECIES (ID_ESPECIE);
ALTER TABLE DB_ESPERANCA_VIVA.ANIMAIS ADD CONSTRAINT FK_RACA FOREIGN KEY(ID_RACA) REFERENCES DB_ESPERANCA_VIVA.RACAS (ID_RACA);
ALTER TABLE DB_ESPERANCA_VIVA.ANIMAIS ADD CONSTRAINT FK_SITUACAO FOREIGN KEY(ID_SITUACAO) REFERENCES DB_ESPERANCA_VIVA.SITUACOES (ID_SITUACAO);


CREATE TABLE DB_ESPERANCA_VIVA.DESPESAS_MEDICAS(

    ID_DESPESA INT AUTO_INCREMENT,
    ID_ANIMAL INT NOT NULL,
    DESPESA_GERADA VARCHAR(30),
    VALOR_DESPESA DECIMAL(8,2),
    DATA_DESPESA DATE,
    PRIMARY KEY (ID_DESPESA)

);

ALTER TABLE DB_ESPERANCA_VIVA.DESPESAS_MEDICAS ADD CONSTRAINT FK_ANIMAL FOREIGN KEY(ID_ANIMAL) REFERENCES DB_ESPERANCA_VIVA.ANIMAIS (ID_ANIMAL);

CREATE TABLE DB_ESPERANCA_VIVA.CLIENTES(

    ID_CLIENTE INT AUTO_INCREMENT,
    NOME VARCHAR(70),
    CPF_CNPJ VARCHAR(14),
    DATA_NASCTO DATE,
    GENERO CHAR(1),
    ESTADO_CIVIL CHAR(1),
    PRIMARY KEY (ID_CLIENTE)

);


CREATE TABLE DB_ESPERANCA_VIVA.TELEFONES(

    ID_TELEFONE INT AUTO_INCREMENT,
    ID_CLIENTE  INT NOT NULL,
    TELEFONE_CELULAR VARCHAR(18),
    PRIMARY KEY (ID_TELEFONE)

);

ALTER TABLE DB_ESPERANCA_VIVA.TELEFONES ADD CONSTRAINT FK_CLIENTE_1 FOREIGN KEY(ID_CLIENTE) REFERENCES DB_ESPERANCA_VIVA.CLIENTES (ID_CLIENTE);

CREATE TABLE DB_ESPERANCA_VIVA.EMAILS(

    ID_EMAIL INT AUTO_INCREMENT,
    ID_CLIENTE  INT NOT NULL,
    EMAIL VARCHAR(30),
    PRIMARY KEY (ID_EMAIL)

);

ALTER TABLE DB_ESPERANCA_VIVA.EMAILS ADD CONSTRAINT FK_CLIENTE_2 FOREIGN KEY(ID_CLIENTE) REFERENCES DB_ESPERANCA_VIVA.CLIENTES (ID_CLIENTE);

CREATE TABLE DB_ESPERANCA_VIVA.ENDERECOS(

    ID_ENDERECO INT AUTO_INCREMENT,
    ID_CLIENTE  INT NOT NULL,
    CEP VARCHAR(10),
    LOGRADOURO VARCHAR(70),
    NUMERO SMALLINT,
    OBS VARCHAR(25),
    CIDADE VARCHAR(30),
    ESTADO VARCHAR(20),
    PRIMARY KEY (ID_ENDERECO)

);

ALTER TABLE DB_ESPERANCA_VIVA.ENDERECOS ADD CONSTRAINT FK_CLIENTE_3 FOREIGN KEY(ID_CLIENTE) REFERENCES DB_ESPERANCA_VIVA.CLIENTES (ID_CLIENTE);

CREATE TABLE DB_ESPERANCA_VIVA.DOACOES(

    ID_DOACAO INT AUTO_INCREMENT,
    ID_CLIENTE  INT NOT NULL,
    VALOR_DOACAO DECIMAL(8,2),
    DATA_DOACAO DATE,
    METODO_PAGTO VARCHAR(20),
    PRIMARY KEY (ID_DOACAO)

);

ALTER TABLE DB_ESPERANCA_VIVA.DOACOES ADD CONSTRAINT FK_CLIENTE_4 FOREIGN KEY(ID_CLIENTE) REFERENCES DB_ESPERANCA_VIVA.CLIENTES (ID_CLIENTE);

